export const ussdBanks = [
  { name: "Access bank", value: "044" },
  { name: "Ecobank", value: "050" },
  { name: "Fidelity bank", value: "070" },
  { name: "First bank of Nigeria", value: "011" },
  { name: "First city monument bank (FCMB)", value: "214" },
  { name: "Guaranty trust bank", value: "058" },
  { name: "Heritage bank", value: "030" },
  { name: "Keystone bank", value: "082" },
  { name: "Stanbic IBTC bank", value: "221" },
  { name: "Sterling bank", value: "232" },
  { name: "Union bank", value: "032" },
  { name: "United bank for Africa (UBA)", value: "033" },
  { name: "Unity Bank", value: "215" },
  { name: "VFD microfinance bank", value: "090110" },
  { name: "Wema bank", value: "035" },
  { name: "Zenith bank", value: "057" },
];
